name: Daily2Do CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment happens after successful build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for server deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to production server
      run: |
        ssh -o StrictHostKeyChecking=no appserver@52.146.19.201 << 'EOF'
          # Check if Node.js is installed
          if ! command -v node &> /dev/null
          then
            echo "Node.js not found, installing..."
            # Install Node.js (if necessary)
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
          fi

          # Check if npm is installed
          if ! command -v npm &> /dev/null
          then
            echo "npm not found, installing..."
            sudo apt install -y npm
          fi

          # Navigate to your project directory
          cd /home/appserver/daily2do

          # Pull the latest changes from the main branch
          git pull origin main

          # Install project dependencies
          npm install

          # Start the application
          npm run start
        EOF

