name: Daily2Do CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        /home/appserver/.nvm/versions/node/v23.6.0/bin/npm install

#    - name: Run tests
#      run: |
#        npm test  # Only if you have tests

#    - name: Build your app (if applicable)
#      run: |
#        npm run build  # If you have a build step

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for server deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to production server
      run: |
        ssh -o StrictHostKeyChecking=no appserver@52.146.19.201 << 'EOF'
          cd /home/appserver/daily2do
          git pull origin main
          /home/appserver/.nvm/versions/node/v23.6.0/bin/npm install
          /home/appserver/.nvm/versions/node/v23.6.0/bin/npm run start
        EOF
