# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SERVER_IP: 52.146.19.201
          USERNAME: appserver
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          APP_DIR: /home/appserver/daily2do
          REPO_URL: https://github.com/arnobferdous/Daily2Dos.git
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "bash -lc '
            if [ ! -d \"$APP_DIR/.git\" ]; then
              /usr/bin/git clone $REPO_URL $APP_DIR
            fi
            cd $APP_DIR
            /usr/bin/git pull origin main
            /home/appserver/.nvm/versions/node/v23.6.0/bin/npm install
            /home/appserver/.nvm/versions/node/v23.6.0/bin/pm2 restart all
          '"
        
